name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  Build-Win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Download source code
        shell: cmd
        run: |
          git clone https://github.com/glfw/glfw.git
          cd glfw
          git checkout 7b6aead9fb88b3623e3b3725ebb42670cbe4c579
          
      - name: Build library
        shell: cmd
        run: |
          xcopy /y /v /s /e glfw
          mkdir upload
          mkdir upload\Debug
          mkdir upload\include
          mkdir upload\Release
          cmake -B build -D BUILD_SHARED_LIBS=ON -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_TESTS=OFF -D GLFW_BUILD_DOCS=OFF
          cmake --build build --config Debug
          copy /y /v build\src\Debug\glfw3.dll upload\Debug
          copy /y /v build\src\Debug\glfw3dll.lib upload\Debug\glfw3dlld.lib
          rmdir /s /q build
          cmake -B build -D BUILD_SHARED_LIBS=ON -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_TESTS=OFF -D GLFW_BUILD_DOCS=OFF
          cmake --build build --config Release
          copy /y /v build\src\Release\glfw3.dll upload\Release
          copy /y /v build\src\Release\glfw3dll.lib upload\Release
          xcopy /y /v /s /e glfw\include upload\include
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: ${{github.workspace}}/upload
          if-no-files-found: ignore
          retention-days: 0
